name: Setup Python
description: Checkout the repository, setup python, and install dependencies
inputs:
  python-version:
    description: Python version to use
    required: true
  rust-version:
    description: Rust version to use
    required: true
runs:
  using: composite
  steps:
    - name: Setup python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: "pip"

    - name: Setup Rust ${{ inputs.rust-version }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust-version }}

    - name: Install dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
