name: Setup Python
description: Checkout the repository, setup python, and install dependencies
inputs:
  python-version:
    description: Python version to use
    required: true
  poetry-version:
    description: Poetry version to use
    required: false
    default: "2.0.1"
  rust-version:
    description: Rust version to use
    required: false
    default: "1.80.0"
runs:
  using: composite
  steps:
    - name: Install Poetry
      shell: bash
      env:
        POETRY_VERSION: ${{ inputs.poetry-version }}
      run: pipx install "poetry==$POETRY_VERSION"

    - name: Setup python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'poetry'

    - name: Setup Rust ${{ inputs.rust-version }}
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ inputs.rust-version }}

    - name: Install dependencies
      shell: bash
      run: poetry install --all-groups --all-extras
